#!/bin/bash
# Organize and rename existing figures to match publication numbering scheme
#
# Usage: bash scripts/organize_paper_figures.sh

set -e

FIGURES_DIR="results/v15_production/figures"
echo "=========================================="
echo "ORGANIZING PUBLICATION FIGURES"
echo "=========================================="
echo "Directory: $FIGURES_DIR"
echo ""

cd "$(dirname "$0")/.." || exit 1

# Create backup directory
BACKUP_DIR="${FIGURES_DIR}/backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
echo "Creating backup: $BACKUP_DIR"
cp -r "$FIGURES_DIR"/*.png "$BACKUP_DIR/" 2>/dev/null || echo "  No existing PNGs to backup"
echo ""

# Map existing figures to new numbering scheme
echo "Renaming figures to publication scheme..."

# Figure 2: Already generated by make_paper_figures.py
# fig02_basis_and_correlation.png ✓

# Figure 5: Hubble diagram (already generated)
# fig05_hubble_diagram.png ✓

# Figure 6: Residual diagnostics (already generated)
# fig06_residual_diagnostics.png ✓

# Figure 7: Alpha evolution (already generated)
# fig07_alpha_vs_z.png ✓

# Figure 9: Holdout validation
if [ -f "$FIGURES_DIR/holdout_validation.png" ]; then
    echo "  Renaming holdout_validation.png → fig09_holdout_validation.png"
    mv "$FIGURES_DIR/holdout_validation.png" "$FIGURES_DIR/fig09_holdout_validation.png"
fi

# Figure 10: Per-survey residuals (already generated if survey column exists)
# fig10_per_survey_residuals.png ✓ (or skipped)

# Move old/supplementary figures to supplementary directory
SUPP_DIR="${FIGURES_DIR}/supplementary"
mkdir -p "$SUPP_DIR"

# Move validation plots to supplementary
for fig in figure1_alpha_pred_validation.png figure2_wiring_bug_detection.png figure3_stage3_guard.png; do
    if [ -f "$FIGURES_DIR/$fig" ]; then
        echo "  Moving $fig → supplementary/"
        mv "$FIGURES_DIR/$fig" "$SUPP_DIR/"
    fi
done

# Move other diagnostic figures to supplementary
for fig in basis_correlation.png monotonicity_diagnostic.png composite_all_figures.png; do
    if [ -f "$FIGURES_DIR/$fig" ]; then
        echo "  Moving $fig → supplementary/"
        mv "$FIGURES_DIR/$fig" "$SUPP_DIR/"
    fi
done

echo ""
echo "=========================================="
echo "ORGANIZATION COMPLETE"
echo "=========================================="
echo ""
echo "Publication-ready figures:"
ls -1 "$FIGURES_DIR"/fig*.png 2>/dev/null || echo "  (run make_paper_figures.py first)"
echo ""
echo "Supplementary figures:"
ls -1 "$SUPP_DIR"/*.png 2>/dev/null || echo "  (none)"
echo ""
echo "Backup saved to: $BACKUP_DIR"
echo ""
echo "Next steps:"
echo "  1. Review figures in: $FIGURES_DIR"
echo "  2. Generate Fig 3 (corner plot) and Fig 4 (MCMC traces) from MCMC samples if needed"
echo "  3. Generate Fig 8 (A/B/C comparison) from comparison results"
echo "  4. Create Fig 1 (concept schematic) manually"
