name: CI
on:
  push:
  pull_request:
defaults:
  run:
    working-directory: NuclidePredictionCurve
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Verify data checksum
        run: |
          python - << 'PY'
import hashlib, sys
h = hashlib.sha256(open("NuMass.csv","rb").read()).hexdigest()
expect = "<PUT_SHA256>"  # replace with the real hash when ready
print("Checksum:", h)
sys.exit(0 if (expect.startswith("<") or h==expect) else 1)
PY
      - name: Run tests
        run: pytest -q

